services:
  app:
    image: golang:1.20
    volumes:
      - ..:/workspace
    working_dir: /workspace
    ports:
      - "3000:3000"
    depends_on:
      - redis
    command: sleep infinity

  redis:
    image: redis:alpine
